name: Application CI
on: [push, pull_request]
jobs:
  pipeline:
    name: jhforge pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup: Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      - name: 'Setup: update npm'
        run: npm install -g npm
      - name: 'Setup: Java'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11.x'
      - name: 'Setup: check'
        run: |
          node -v
          npm -v
          java -version
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Init: install Node.js packages'
        run: npm install
      - name: 'Test: run backend test'
        run: |
          chmod +x mvnw
          ./mvnw clean verify
