name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: Node.js'
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.13.0
      - name: 'Setup: update npm'
        run: npm install -g npm
      - name: 'Setup: Java 17'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: 'Setup: check tools'
        run: |
          node -v
          npm -v
          java -version
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Init: install Node.js packages'
        run: npm ci
      - name: 'Check: prettier'
        run: npm run prettier:check
      - name: 'Test: run backend tests'
        run: |
          chmod +x mvnw
          ./mvnw clean verify
      - name: 'Artifact: upload JaCoCo report'
        uses: actions/upload-artifact@v2
        with:
          name: jacoco
          path: '${{ github.workspace }}/target/jacoco/jacoco.xml'
          retention-days: 1
      - name: 'Artifact: upload JAR'
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: '${{ github.workspace }}/target/*.jar'
          retention-days: 1
  generation:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: Node.js'
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.13.0
      - name: 'Setup: update npm'
        run: npm install -g npm
      - name: 'Setup: Java 17'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: 'Setup: check tools'
        run: |
          node -v
          npm -v
          java -version
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Artifact: download JAR'
        uses: actions/download-artifact@v2
        with:
          name: jar
      - name: 'Generation: generate Beer project'
        run: |
          mv *.jar tests/
          cd tests/
          ./start.sh
          ./generate.sh
          ls -al /tmp/beer/
          ./stop.sh
      - name: 'Test: Beer project'
        run: |
          cd /tmp/beer/
          chmod +x mvnw
          ./mvnw clean verify
  codecov:
    needs: generation
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Artifact: download JaCoCo report'
        uses: actions/download-artifact@v2
        with:
          name: jacoco
      - name: 'Codecov: sending analyzis...'
        uses: codecov/codecov-action@v2
        with:
          files: jacoco.xml
          fail_ci_if_error: true
          verbose: true
